version: "3.3"

services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - "C:/Users/Vladimir/IdeaProjects/demo/src/main/resources/prometheus.yml:/etc/prometheus/prometheus.yml"
      - "C:/Users/Vladimir/IdeaProjects/demo/src/main/resources/down_rule.yml:/etc/prometheus/down_rule.yml"
  alert-manager:
    image: prom/alertmanager:latest
    ports:
      - 9093:9093
    volumes:
      - "C:/Users/Vladimir/IdeaProjects/demo/src/main/resources/alertmanager.yml:/etc/alertmanager/alertmanager.yml"