global:
  scrape_interval: 5s
  external_labels:
    monitor: 'my-monitor'

scrape_configs:
  - job_name: 'prometheus'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ["host.docker.internal:8080"]
      - targets: ["host.docker.internal:8081"]
  - job_name: 'mysql-exporter'
    file_sd_configs:
      - files:
        - "sd/targets-mysql-exporter.yml"

rule_files:
  - "down_rule.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alert-manager:9093"